
senzingStack:
  enabled: true
  namespace: senzing
  repoURL: https://hub.senzing.com/charts
  components:
  - chartName: senzing-console
    targetRevision: 2.3.1
    enabled: true
    helmValues: ""
  - chartName: senzing-api-server
    targetRevision: 2.4.2
    enabled: false
    helmValues: ""
  - chartName: senzing-stream-loader
    targetRevision: 2.4.3
    enabled: false
    helmValues: ""
  - chartName: senzing-redoer
    targetRevision: 2.4.2
    enabled: false
    helmValues: ""
  - chartName: swaggerapi-swagger-ui
    targetRevision: 2.3.0
    enabled: false
    helmValues: ""
  - chartName: senzing-debug
    targetRevision: 1.3.0
    enabled: true
    helmValues: ""
  - chartName: senzing-init-postgresql
    targetRevision: 1.0.0
    enabled: false
    helmValues: ""
  - chartName: senzing-postgresql-client
    targetRevision: 2.2.0
    enabled: false
    helmValues: ""
  